apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-nfs-pod
spec:
  restartPolicy: Never
  containers:
  - name: test-nfs
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo 'Success' > /mnt/SUCCESS && ls -l /mnt && sleep 3600"]
    volumeMounts:
    - name: nfs-pvc
      mountPath: "/mnt"
  volumes:
  - name: nfs-pvc
    persistentVolumeClaim:
      claimName: test-nfs-pvc
